ID = "auth_id"
EVENTNAME = "event_name"
PREV_SC = "previous_screen_class"
CURR_SC = "screen_class"
USETIME = "use_time_msec"
TIMESTAMP = "event_timestamp_w_timezone"
FORMATTED_TIMESTAMP = "fomatted_event_timestamp_w_timezone"